spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: firoze28
    url: jdbc:mysql://localhost:3306/cafedb
server:
  port: 8086
logging:
  level:
    org:
      springframework:
        security: debug